### ISSUE TITLE
BreadcrumbList Microdata

### ISSUE THREAD

**Issue by m-e-h** [justintadlock/breadcrumb-trail#11]
Schema.org added BreadcrumbList not too long ago. http://schema.org/BreadcrumbList
Woulda done a pull request but not sure how much of it you'd want to implement.

**Comment by justintadlock** [comment]
I've been thinking about this.  The biggest hurdle I see is the change in the HTML, which will break back compatibility (styling) on some sites.  I'd like to move us to using an unordered list, regardless of microdata, which I think is the best direction.

So, this needs to be handled on two fronts:

* Change over to a `<ul>` structure.  We'll also want to remove the `separator` argument and leave that for CSS.
* Then, add in the microdata.

I think it's important to get the HTML down first.

**Comment by m-e-h** [comment]
Removing spans and seps sounds good. But yeah, back compat sounds tough. Lists could reek havoc on people's breadcrumbs. Aligning them vertical and possibly adding bullets.

Looking around, I see 2 common conventions: `ul/ol > li`, or `nav > a/span`
Is there an accessibility reason `ul` is better?
If not, maybe just remove the `sep`, possibly add `span` around each `a`(for consistency and microdata) and stick with what you have.

**Comment by justintadlock** [comment]
I'm not sure if there's an accessibility reason, per say.  I do think there's a bit more structure, which is probably good all around from a markup standpoint.  A list would be far easier to manipulate stylistically than what we have now.  I suppose each element could be wrapped up into a `<span>` to accomplish the same thing, but we'll have some weird `<span><a><span></span></a></span>` mixes when we add the microdata. 

I could add some small CSS for the breadcrumbs here in the plugin to handle any back compatibility problems.

**Comment by m-e-h** [comment]
I guess that could turn into a giant `span` :shit: cluster once microdatas added. And yeah, it would only take one or two css declarations to normalize the `ul`. 
Since your adding css would you add the `::before` selector for the separator? Would that be configurable like it is now? `'separator' => ' / '`. I'd guess that would handle back compatibility for many folks.

**Comment by justintadlock** [comment]
Yep, we'd need to use `::before` or `::after`.  The `separator` argument would still need to go because the CSS would be called on `wp_head` but the `breadcrumb_trail()` function wouldn't execute until later in the page.

**Comment by justintadlock** [comment]
Here's a rough first pass at using a `<ul>`: https://github.com/justintadlock/breadcrumb-trail/commit/9e460a5653f3bbab1a7cceb4296fdeb05e2fb981

**Comment by m-e-h** [comment]
Here's how it looks with my existing styles. 

**with `block` applied to `.trail-items`**

![with block](https://googledrive.com/host/0B-B36bvbQPRlanJRazU1NzZOS2M/breadblock.png)

**with `inline-block` applied to `.trail-items`**

![with inline-block](https://googledrive.com/host/0B-B36bvbQPRlanJRazU1NzZOS2M/breadinline.png)

Also, I've defined a `margin-bottom` on my `ul`s so there's spacing below the breadcrubs. Not sure if that's common or not.

**Comment by justintadlock** [comment]
Yep, I forgot about "browse".  My thinking was that should be a header.  I matched it up with WP's newer `the_posts_pagination()`, which uses an `<h2>`.  I'll probably add an option to change that up a bit later + better markup options.

Anyway, I made some CSS adjustments too in https://github.com/justintadlock/breadcrumb-trail/commit/e4e43c60b5bf9cbc799b0f62b3d0ad17ba6166df.

**Comment by m-e-h** [comment]
Yes sir. Breadcrumbs look the same with that new code as with HC 2.1(on my theme anyway).

One issue I did have because I'm minifying my html output is the two spaces before `  role="navigation"`https://github.com/justintadlock/breadcrumb-trail/blob/1.0/inc/breadcrumbs.php#L132
The script I'm using removes 2 spaces but not one so I get `<divrole=`, but that's kind of a problem with my script.

And one more question. Why not put the `trail-begin` class on the `<li>` instead of adding a `<span>`?

**Comment by justintadlock** [comment]
I'll look into the space issue.

As for the `trail-begin` class, that's something I'd like to work into the `<li>`.  I wanted to get the base list structure in first.

**Comment by m-e-h** [comment]
For reference, here is Google's code example for schema.org breadcrumbs in search.
https://developers.google.com/structured-data/breadcrumbs

**Comment by m-e-h** [comment]
Hmm. Actually that link isn't showing the new breadcrumb markup. Hopefully it'll get updated.

**Comment by justintadlock** [comment]
Check the latest commit. I think it's mostly done now.

**Comment by m-e-h** [comment]
You do it right man. Even included the position numbers!
Looks much simpler to style also.

**Comment by justintadlock** [comment]
I cleaned up the theme support CSS stuff. We can open new tickets for any further issues. I'll close this one as fixed.
