### ISSUE TITLE
output only text, no links

### ISSUE THREAD

**Issue by whysthatso** [justintadlock/breadcrumb-trail#14]
hey,
i'd like to use the list as text-only, no links, and i'm kind of thinking i should look at the hooks, but i have no idea how to start. is there some easy way to filter out the a tags, and just output the text?

cheers

**Comment by justintadlock** [comment]
The support forum is located here: http://themehybrid.com/board/forums/plugins

In general though, look into the `breadcrumb_trail_items` hook.
