### ISSUE TITLE
Breadcrumb not showing on mobile

### ISSUE THREAD

**Issue by lorenzo93** [justintadlock/breadcrumb-trail#15]
Hi,
I just installed your plugin and from the computer browser it works great!
Then I tryed the mobile version but I don't know why it is not showing anything than the separator "/". I've attached the screenshot of the html code relative to the plugin and I find out that the problem seems related to the <span intemprop="name">...</span> tag.
I've tryed with chrome to modify the HTML and removing the tag, leaving only the content it shows!

Thank you very much

PS "Reti" is the name of the wordpress page but it is not related, it happens in all pages

![screenshot_1](https://cloud.githubusercontent.com/assets/12275050/10179725/36230b2c-6708-11e5-8d16-b1b33139502c.png)
![screenshot_2](https://cloud.githubusercontent.com/assets/12275050/10179746/5edfd81a-6708-11e5-8e3f-ec1570beda94.png)

**Comment by justintadlock** [comment]
The support forum is here: http://themehybrid.com/board/topics

I'm tempted to close this ticket as it doesn't seem to be a bug report, but rather a styling issue on your end.  I'll wait for your feedback if you think there's a legit bug with the plugin itself.

**Comment by lorenzo93** [comment]
I'm Sorry, my mistake.

As I changed the theme to the default twentyfifteen it start showing again!
