### ISSUE TITLE
Compliance with Google Structured Data & W3C

### ISSUE THREAD

**Issue by shivanandwp** [justintadlock/breadcrumb-trail#16]
Not much of a schema expert. I just noted a few things when looking at https://developers.google.com/structured-data/breadcrumbs?hl=en and http://justintadlock.com/topics/wordpress

1) Apparently the items could use itemprop="item". May be have a filter to do this insertion.
2) May be get rid of UL and LIs with help of filters like at http://justintadlock.com/topics/wordpress
3) Not sure if Google's recommendations should win over W3C validations. But here's a simple html5 file that fails.
[Untitled-1.txt](https://github.com/justintadlock/breadcrumb-trail/files/46424/Untitled-1.txt)

**Comment by justintadlock** [comment]
I'm up for suggestions on how to make the two things work together nicely.

I seperated out 1 and 2 into their own tickets since they are unrelated:

1) See: https://github.com/justintadlock/breadcrumb-trail/issues/17
2) See: https://github.com/justintadlock/breadcrumb-trail/issues/17

**Comment by justintadlock** [comment]
Closing this since the separated tickets were closed.
