### ISSUE TITLE
(Suggestion) Avoid quotes issue with search results label

### ISSUE THREAD

**Issue by mikedance** [justintadlock/breadcrumb-trail#24]
Currently the default search label is:

`Search results for &#8220;%s&#8221;`

So when the user searches for something in quotes, the output looks like this:

`Search results for ""sample search query""`

This is basically expected from a developer POV, but it looks a lot like a bug (or at least a typo) to the end user.

To avoid, I usually filter the label to:

`Search results for: <span>%s</span>`

The colon does the same job the quotes used to, and the extra &lt;span&gt; allows a developer to optionally bold or whatnot.

**Comment by justintadlock** [comment]
I actually like this suggestion.  If I decide to change it here, I'll need to change it in my framework too just for consistency.  It's a good idea though.
