### ISSUE TITLE
Post/custom-post terms not reversed correctly

### ISSUE THREAD

**Issue by evolvd** [justintadlock/breadcrumb-trail#25]
Hi,

I had a weird item order eg:
home > custom-post type archive > level 3 term > level 2 term > level 1 term > level 4 term > post

tracked it down to `add_term_parents` function in `breadcrumbs.php`

`// If we have parent terms, reverse the array to put them in the proper order for the trail.`
		`if ( !empty( $parents ) )
			$this->items = array_merge( $this->items, $parents );`

as the comment indicates, `$parents` should be `array_reversed($parents)`

**Comment by justintadlock** [comment]
Sorry, I fixed this a while back.  Just haven't pushed it live.

Fixed in: https://github.com/justintadlock/breadcrumb-trail/commit/8e65940b293c30558979f3adc156480344d3c62a
