### ISSUE TITLE
Deprecated function

### ISSUE THREAD

**Issue by MrAndreius** [justintadlock/breadcrumb-trail#37]
https://github.com/justintadlock/breadcrumb-trail/blob/c7e4c0f3844f12241a154d45b0494bea4a040734/inc/breadcrumbs.php#L1073

wp-includes\deprecated.php:3826 - _usort_terms_by_ID is deprecated since version 4.7.0! Use wp_list_sort() instead.

breadcrumb_trail, Breadcrumb_Trail->__construct, Breadcrumb_Trail->add_items, Breadcrumb_Trail->add_singular_items, Breadcrumb_Trail->add_post_terms, usort, _usort_terms_by_ID, _deprecated_function

**Comment by justintadlock** [comment]
Fixed a year ago: https://github.com/justintadlock/breadcrumb-trail/commit/df8d0ac968e40523da5bcf1df6a462127f2ee389

**Comment by Rarst** [comment]
Did this not make it into 1.1 which seems to have been target for it? Still the issue downstream in Hybrid Core as well.

**Comment by justintadlock** [comment]
Version 1.1.0: https://github.com/justintadlock/breadcrumb-trail/blob/1.1.0/inc/breadcrumbs.php#L1068-L1073

The latest HC, which is still using 1.1.0-dev, also has this change: https://github.com/justintadlock/hybrid-core/blob/4.0.0/ext/breadcrumb-trail.php#L1056-L1061

**Comment by Rarst** [comment]
Ok, I must have looked at it wrong somehow, sorry. :)
