### ISSUE TITLE
Last Trail generates error for Google Structured Data test.

### ISSUE THREAD

**Issue by premanshup** [justintadlock/breadcrumb-trail#42]
Hello, 

When the breadcrumb trail is added in WordPress and tested in the Google Structured Data tool, it shows the following error:

`The value provided for item.id must be a valid URL.`

Screenshot: https://cl.ly/4a9c13f88612

We did a little research and found that the last item should also have a link.

Right now, there is no link added for the last item which generates the above issue.

Can you please look into this and add a link or is there any other workaround that we can use to resolve this error?

**Comment by justintadlock** [comment]
There's a `show_trail_end` argument in the Hybrid Breadcrumbs project, which allows you to disable the final breadcrumb item: https://github.com/justintadlock/hybrid-breadcrumbs/

The Breadcrumb Trail plugin will be switching over to using that project in the next version.  So, there are no plans to specifically address anything beyond security issues within Breadcrumb Trail for now.

I'm also likely to allow the last item to be linkable when possible as well in that project.

**Comment by premanshup** [comment]
Thank you for the information. Hybrid Breadcrumbs is looking great. Yes, maybe an argument to enable the last item link can be added.

Again thank you!
